[project]
name = "file_sharing_DRF_server"
version = "0.6.7"
dependencies = [
    "boto3>=1.43.81",
    "django>=6.1",
    "django-storages>=1.14.6",
    "djangorestframework>=3.18.0",
    "djangorestframework-simplejwt>=5.5.1",
    "psycopg[binary]>=3.3.4",
    "pytest>=9.1.1",
    "pytest-django[django]>=4.14.0",
    "python-dotenv>=1.2.3",
]

[tool.pytest]
DJANGO_SETTINGS_MODULE = "file_sharing.settings"
python_files = ["test.py", "tests.py", "test_*.py", "*_tests.py"]
addopts = [
  "--import-mode=importlib",
]

[dependency-groups]
dev = [
    "basedpyright>=1.39.10",
    "django-stubs>=6.1.0",
    "ruff>=0.16.4",
    "ty>=0.0.75",
]
