# Generated by Django 6.1 on 2026-08-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_file_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='extention',
            new_name='extension',
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
